version: '3'
services:
  stockmarket-mysql:
    image: mysql:8.0.18
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - C:/Users/Admin/Desktop/MODProject/stockmarketdemo:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
       
  eureka-discovery-service:
    image: eureka-discovery-app
    build: ./microservices/eureka-discovery-service
    ports:
      - 8761:8761
      
  authentication-service:
    image: authentication-app
    build: ./microservices/authentication-service
    ports:
      - 8083:8083
    depends_on:
      - stockmarket-mysql
      - eureka-discovery-service
    links:
      - stockmarket-mysql
      - eureka-discovery-service
      
  company-service:
    image: company-app
    build: ./microservices/company-service
    ports:
      - 8085:8085
    depends_on:
      - stockmarket-mysql
      - eureka-discovery-service
    links:
      - stockmarket-mysql
      - eureka-discovery-service
      
  fileUpload-service:
    image: fileUpload-app
    build: ./microservices/file-upload-service
    ports:
      - 8081:8081
    depends_on:
      - stockmarket-mysql
      - eureka-discovery-service
    links:
      - stockmarket-mysql
      - eureka-discovery-service   
      
  zuul-gateway:
    image: zuul-gateway
    build: ./microservices/zuul-gateway
    ports:
      - 8082:8082
    depends_on:
      - stockmarket-mysql
      - eureka-discovery-service
      - company-service
      - file-upload-service
      - authentication-service
      
    links:
      - stockmarket-mysql
      - eureka-discovery-service
      - authentication-service
      - file-upload-service
      - product-service
      
  angular:
    image: angular-app
    build: ./webapp/dist
    ports:
      - 4200:80
    depends_on:
      - stockmarket-mysql
      - eureka-discovery-service
      - company-service
      - file-upload-service
      - authentication-service
      - zuul-gateway
      
    links:
      - stockmarket-mysql
      - eureka-discovery-service
      - authentication-service
      - company-service
      - file-upload-service
      - zuul-gateway